# define a task to delete all files with the extensions
# aux, fls, fdb_latexmk, log, synctex.gz
#

clean:
	rm -f *.aux *.fls *.fdb_latexmk *.log *.synctex.gz *.vrb *.toc *.snm *.nav *.out

cleanpdf:
	rm -f *.pdf

cleanall: clean cleanpdf
